### ISSUE TITLE
*Fix Bug*

### ISSUE THREAD

**Issue by SdevWeb7** [SdevWeb7/Dev-js#1]
Nous avons un problème avec le lien "chaine youtube" de la partie "Ressources Utiles" du cours "VS-Code".  "https" a été oublié cela ne nous envoi pas vers le lien.
Cela est problématique, pouvez vous Fix ce bug au plus vite svp.
Merci.

**Comment by houseOftaz** [comment]
problem solved boss

**Comment by SdevWeb7** [comment]
Merci infiniment !!!

**Comment by houseOftaz** [comment]
de rien brow
